# Generated by Django 5.1.7 on 2025-03-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=50)),
                ('qr_code', models.ImageField(blank=True, upload_to='qrcodes/')),
            ],
        ),
    ]
